version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo_mern_jwt
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
